{
    'name': 'student_management',
    'version': '1.0.0',
    'summary': 'Student Management System',
    'description': 'A module to manage student information, courses, and grades.',
    'author': 'Nguyen Van Bac',
    'category': 'Education',
    'depends': ['base', 'mail'],
    'data': [
        'security/student_management_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/mail_template_data.xml',
        'data/ir_cron_data.xml',
        'report/student_report_templates.xml',
        'report/student_report.xml',
        'views/student_views.xml',
        'views/course_views.xml',
        'views/teacher_views.xml',
        'views/classroom_views.xml',
        'views/enrollment_views.xml',
        'wizard/enroll_students_wizard_views.xml',
        'views/menu_views.xml',
    ],
    'demo': [
        'demo/demo_data.xml',
    ],
    'installable': True,
    'application': True,
    'autoinstall': False,
    'license': 'LGPL-3',
}